module.exports = {
    profileController: require("./profileController"),
    skillController:require("./skillController"),
    educationSController:require("./educationController"),
    workExperienceController:require("./workExperienceController"),
    volunteerExperienceController:require("./volunteerExperController"),
    awardandhonorsController:require("./awardandhonorsController"),
    licenceandcertificateController:require("./licenceandcertificateController"),
    language:require("./languageController"),
    projectUnderTakenController:require("./projectUnderTakenController"),
    addLink:require("./addlinkController"),
    projectUnderTakenTeamMemberContoller:require("./projectUnderTakenTeamMemberController"),
    projectUnderTakenMediaController:require("./projectUnderTakenMediaController"),
    resumeController:require("./resumeController"),
  }